exclude: >
    (?x)(
        LICENSE$|
        SECURITY$|
        README$
    )
repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies: [flake8-bugbear, flake8-logging-format]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        exclude: (^speedtest/tests/, ^speedtest/docs/)

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black]
        language_version: python3

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.9
        args:
          - --skip-string-normalization
          # these folders wont be formatted by black
          - --exclude="""\.git |
            \.__pycache__|
            \.tox|
            \.venv|
            _build|
            build|
            dist"""

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
      - id: fix-encoding-pragma
