# -*- coding: utf-8 -*-
from setuptools import find_packages, setup


setup(
    name='speedtest',
    version='1.0.0',
    packages=find_packages(),
    entry_points={'console_scripts': ['speedtest = speedtest.__main__:main']},
    install_requires=[
        'click==8.0.3',
        'codetiming==1.4',
        'jsonschema==4.1.0',
        'jsonpath-ng==1.5.3',
        'pytest==6.2.5',
        'pytest-cov==3.0.0',
        'Jinja2==3.1.4',
        'python-dateutil>=2.8.0',
        'types-python-dateutil',
    ],
    classifiers=[
        'Development Status :: 4 - Beta',
        'Environment :: Console',
        'Intended Audience :: System Administrators',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Topic :: Internet',
        'Topic :: System :: Networking',
        'Topic :: Utilities',
    ],
    author='cbabil',
    author_email='cbabil@users.noreply.github.com',
    description='A Python wrapper for the Ookla Speedtest CLI with JSON schema validation and templating support',
    long_description='A comprehensive Python tool that wraps the Ookla Speedtest CLI, validates output against JSON schemas, and supports custom templating for various output formats including InfluxDB.',
    long_description_content_type='text/plain',
    url='https://github.com/cbabil/speedtest',
    project_urls={
        'Bug Reports': 'https://github.com/cbabil/speedtest/issues',
        'Source': 'https://github.com/cbabil/speedtest',
    },
    keywords='speedtest, ookla, network, bandwidth, monitoring, influxdb',
    python_requires='>=3.8',
)
